version: '3'
services:
   mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_TLS_VERSION=TLSv1.2
    ports:
      - $MYSQLDB_LOCAL_PORT:$DB_PORT
    volumes:
      - ./docker_logs/db/db-config:/etc/mysql/conf.d   
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro   
   app:
    depends_on:
       - mysqldb   
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true       
    volumes:
       - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
volumes: 
  docker_logs:
  mysql_data:
  mysql_logs: